baseURL = "https://blogsito.netlify.app/"
disqusShortname = "themefisher-template"
googleAnalytics = ""
paginate = "5"
summaryLength = "20"
theme = "bookworm-light"
title = "Blogcito <3"
[imaging]
quality = "95"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer]]
name = "Privacy"
url = "privacy/"
weight = 3
[[menu.footer]]
name = "Authors"
url = "author/"
weight = 2
[[menu.footer]]
name = "About"
url = "about/"
weight = 1
[[menu.main]]
name = "Terms & Conditions"
parent = "Páginas"
url = "terms-conditions/"
weight = 6
[[menu.main]]
name = "Privacy"
parent = "Páginas"
url = "privacy/"
weight = 5
[[menu.main]]
name = "Elements"
parent = "Páginas"
url = "elements/"
weight = 4
[[menu.main]]
name = "Category"
parent = "Páginas"
url = "categories/"
weight = 3
[[menu.main]]
name = "Tags"
parent = "Páginas"
url = "tags/"
weight = 2
[[menu.main]]
hasChildren = true
name = "Páginas"
url = "#"
weight = 3
[[menu.main]]
name = "Inicio"
url = "/"
weight = 1
[module.hugoVersion]
extended = true
min = "0.87.0"
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "Designed & Developed By [Gethugothemes](https://gethugothemes.com/)"
description = "This is meta description"
favicon = "images/favicon.png"
logo = "images/logo.png"
logo_width = "200px"
mainSections = ["blog"]
search = true
[params.cookies]
enable = false
expire_days = 2
[params.instafeed]
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"
enable = false
instagram_user = "bookworm"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Mulish:wght@500;600;700;800;900&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/instagram-feed/instagram-feed.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = false
preloader = ""
[params.subscription]
enable = true
input_placeholder = "Enter your email"
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
title = "Subscribe for our monthly newsletter."
[params.variables]
black = "#000000"
color_primary = "#01AD9F"
dark = "#152035"
font_primary = "Mulish"
gray = "#747577"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
light = "#FAFAFA"
white = "#ffffff"
[[params.social]]
icon = "lab la-facebook-f"
url = "https://www.facebook.com/"
[[params.social]]
icon = "lab la-twitter"
url = "https://www.twitter.com/"
[[params.social]]
icon = "lab la-instagram"
url = "https://www.instagram.com/"
[[params.social]]
icon = "lab la-linkedin-in"
url = "https://www.linkedin.com/"
